"""nftables adapter: renders and atomically applies the whole ruleset.

The firewall is zone-based (spec §11). Zone membership is expressed as named
interface sets so a network can move between ports/VLANs without rewriting rules.
The entire ruleset is generated as one text blob and applied with `nft -f`, which
is atomic — a syntax error leaves the previous ruleset in place rather than a
half-open firewall.
"""
from __future__ import annotations

import logging
from typing import Any

from ..util import ToolError, run, run_json, run_ok, write_atomic

log = logging.getLogger("sbegw.nft")

TABLE = "sbegw"
RULESET_PATH = "/run/sbegw/nftables.conf"

VERDICTS = {"allow": "accept", "reject": "reject", "drop": "drop"}


def available() -> bool:
    try:
        run(["nft", "--version"], timeout=5.0)
        return True
    except (ToolError, OSError):
        return False


def _quote_set(values: list[str]) -> str:
    return "{ " + ", ".join(values) + " }"


def _proto_expr(protocol: str) -> str:
    return {"tcp": "meta l4proto tcp", "udp": "meta l4proto udp",
            "tcp-udp": "meta l4proto { tcp, udp }",
            "icmp": "meta l4proto icmp", "icmpv6": "meta l4proto icmpv6",
            "esp": "meta l4proto esp", "gre": "meta l4proto gre"}.get(protocol, "")


def _addr_expr(spec: str, side: str, family: str,
               groups: dict[str, Any]) -> str | None:
    """Render a source/destination match. `side` is 'saddr' or 'daddr'."""
    if spec.startswith("group:"):
        name = spec.split(":", 1)[1]
        members = (groups.get("address", {}).get(name) or {}).get("members", [])
        members = [m for m in members if (":" in m) == (family == "ip6")]
        if not members:
            return None
        return f"{family} {side} {_quote_set(members)}"
    if (":" in spec) != (family == "ip6"):
        return None
    return f"{family} {side} {spec}"


def _port_expr(spec: str, side: str) -> str:
    """`side` is 'sport' or 'dport'. Accepts single or range."""
    value = spec.replace("-", "-")
    return f"th {side} {value}"


def _schedule_expr(schedule: dict[str, Any]) -> str:
    """Time-based match using nft's meta hour/day."""
    parts = []
    days = schedule.get("days")
    if days:
        parts.append("meta day " + _quote_set([f'"{d}"' for d in days]))
    start, end = schedule.get("start"), schedule.get("end")
    if start and end:
        parts.append(f'meta hour "{start}"-"{end}"')
    return " ".join(parts)


def render(cfg: dict[str, Any], zone_interfaces: dict[str, list[str]],
           wan_interfaces: dict[str, str]) -> str:
    """Build the complete nftables ruleset for the running config."""
    fw = cfg.get("firewall", {})
    nat = cfg.get("nat", {})
    groups = fw.get("groups", {})
    schedules = fw.get("schedules", {})
    networks = cfg.get("networks", {})

    lines: list[str] = [
        "#!/usr/sbin/nft -f",
        "# generated by sbegw netd — do not edit",
        f"flush ruleset",
        "",
        f"table inet {TABLE} {{",
    ]

    # --- zone interface sets
    for zone, ifaces in sorted(zone_interfaces.items()):
        lines.append(f"    set zone_{zone} {{")
        lines.append("        type ifname")
        if ifaces:
            lines.append("        elements = " + _quote_set(sorted(set(ifaces))))
        lines.append("    }")

    # --- reusable address groups
    for name, group in sorted((groups.get("address") or {}).items()):
        v4 = [m for m in group.get("members", []) if ":" not in m]
        v6 = [m for m in group.get("members", []) if ":" in m]
        if v4:
            lines += [f"    set addr4_{name} {{", "        type ipv4_addr",
                      "        flags interval",
                      "        elements = " + _quote_set(v4), "    }"]
        if v6:
            lines += [f"    set addr6_{name} {{", "        type ipv6_addr",
                      "        flags interval",
                      "        elements = " + _quote_set(v6), "    }"]

    # --- counters per rule so the UI can show hit statistics
    lines.append("")
    lines += _render_input_chain(cfg, zone_interfaces)
    lines += _render_forward_chain(cfg, fw, groups, schedules, networks,
                                   zone_interfaces)
    lines.append("    chain output {")
    lines.append("        type filter hook output priority 0; policy accept;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines += _render_nat_table(cfg, nat, wan_interfaces, networks)
    lines += _render_mangle_table(cfg, wan_interfaces)
    return "\n".join(lines) + "\n"


def _render_input_chain(cfg: dict[str, Any],
                        zone_interfaces: dict[str, list[str]]) -> list[str]:
    """Traffic terminating on the gateway itself."""
    fw = cfg.get("firewall", {})
    policies = fw.get("default_policies", {})
    services = cfg.get("services", {})

    lines = ["    chain input {",
             "        type filter hook input priority 0; policy drop;",
             "        iif lo accept",
             "        ct state established,related accept",
             "        ct state invalid counter drop",
             # ICMP is required for PMTU and IPv6 to work at all.
             "        icmp type { echo-request, destination-unreachable, "
             "time-exceeded, parameter-problem } limit rate 20/second accept",
             "        icmpv6 type { echo-request, destination-unreachable, "
             "packet-too-big, time-exceeded, parameter-problem, nd-router-solicit, "
             "nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, "
             "mld-listener-query, mld-listener-report, mld2-listener-report } accept",
             # DHCPv6 client and RA on WAN.
             "        udp dport 546 accept",
             ]

    for zone, ifaces in sorted(zone_interfaces.items()):
        if zone in ("wan", "gateway"):
            continue
        action = VERDICTS.get(policies.get(f"{zone}->gateway", "reject"), "reject")
        if action == "accept":
            # A zone allowed to reach the gateway still only gets the services
            # the gateway actually offers to it.
            lines.append(f"        iifname @zone_{zone} udp dport {{ 53, 67, 123 }} "
                         "counter accept")
            lines.append(f"        iifname @zone_{zone} tcp dport {{ 53 }} counter accept")
            lines.append(f"        iifname @zone_{zone} tcp dport {{ 443, 80 }} "
                         "counter accept comment \"management UI\"")
            if services.get("ssh", {}).get("enabled"):
                port = services["ssh"].get("port", 22)
                lines.append(f"        iifname @zone_{zone} tcp dport {port} "
                             "counter accept comment \"ssh\"")
        else:
            # Restricted zones still need DNS/DHCP or clients cannot get online.
            lines.append(f"        iifname @zone_{zone} udp dport {{ 53, 67 }} "
                         "counter accept comment \"dns/dhcp only\"")
            lines.append(f"        iifname @zone_{zone} tcp dport 53 counter accept")
            lines.append(f"        iifname @zone_{zone} counter {action}")

    # WAN input: nothing but what NAT/port-forward has already accepted.
    lines.append("        iifname @zone_wan counter drop comment \"wan to gateway\"")
    lines.append("        counter drop")
    lines.append("    }")
    return lines


def _render_forward_chain(cfg: dict[str, Any], fw: dict[str, Any],
                          groups: dict[str, Any], schedules: dict[str, Any],
                          networks: dict[str, Any],
                          zone_interfaces: dict[str, list[str]]) -> list[str]:
    lines = ["    chain forward {",
             "        type filter hook forward priority 0; policy drop;",
             "        ct state established,related accept",
             "        ct state invalid counter drop",
             # MSS clamping for PPPoE / tunnelled WANs.
             "        tcp flags syn tcp option maxseg size set rt mtu",
             ]

    # Frames that enter and leave the SAME bridge are switched, not routed —
    # policing them is the bridge's business, not this chain's. They only appear
    # here at all because br_netfilter is loaded (Docker loads it), and then a
    # zone-based policy has no rule to match: a client bridged onto the WAN
    # alongside the WAN port is iifname br-wan, oifname br-wan, which matches no
    # zone pair and falls through to the drop.
    #
    # Measured: such a client authenticated, associated and completed the 4-way
    # handshake, then disassociated in a loop, because its DHCP never left the
    # box — 112 packets on the fallthrough drop and no offer ever came back.
    # Real bridges only. A VLAN sub-interface of one (br-lan.30) is an L3
    # interface, not a segment we own both ends of, so it stays policed.
    bridges = {i.strip('"') for ifaces in zone_interfaces.values() for i in ifaces
               if i.strip('"').startswith("br-") and "." not in i.strip('"')}
    for bridge in sorted(bridges):
        lines.append(f"        iifname \"{bridge}\" oifname \"{bridge}\" counter "
                     f"accept comment \"switched within {bridge}\"")

    # DNAT'd traffic has already been policy-checked in prerouting.
    lines.append("        ct status dnat counter accept comment \"port forwards\"")

    # --- explicit user rules, ordered, before zone defaults
    rules = sorted([r for r in fw.get("rules", []) if r.get("enabled", True)],
                   key=lambda r: r.get("index", 0))
    for rule in rules:
        for family in _families(rule.get("family", "both")):
            expr = _render_rule(rule, family, groups, schedules)
            if expr:
                lines.append("        " + expr)

    # --- network isolation
    for nid, net in networks.items():
        if net.get("isolation"):
            zone = net.get("zone", "lan")
            lines.append(f"        iifname @zone_{zone} oifname @zone_{zone} "
                         f"counter drop comment \"isolate {nid}\"")
        if not net.get("internet_access", True):
            zone = net.get("zone", "lan")
            lines.append(f"        iifname @zone_{zone} oifname @zone_wan "
                         f"counter reject comment \"no internet: {nid}\"")

    # --- zone-to-zone defaults
    policies = fw.get("default_policies", {})
    for key, action in sorted(policies.items()):
        src, _, dst = key.partition("->")
        verdict = VERDICTS.get(action, "drop")
        lines.append(f"        iifname @zone_{src} oifname @zone_{dst} "
                     f"counter {verdict} comment \"{key}\"")

    lines.append("        counter drop")
    lines.append("    }")
    return lines


def _families(family: str) -> list[str]:
    if family == "ipv4":
        return ["ip"]
    if family == "ipv6":
        return ["ip6"]
    return ["ip", "ip6"]


def _render_rule(rule: dict[str, Any], family: str, groups: dict[str, Any],
                 schedules: dict[str, Any]) -> str | None:
    parts = [f"iifname @zone_{rule.get('src_zone', 'lan')}",
             f"oifname @zone_{rule.get('dst_zone', 'wan')}"]

    protocol = rule.get("protocol", "any")
    if protocol == "icmp" and family == "ip6":
        return None
    if protocol == "icmpv6" and family == "ip":
        return None
    if protocol != "any":
        parts.append(_proto_expr(protocol))

    for field, side in (("src_address", "saddr"), ("dst_address", "daddr")):
        if rule.get(field):
            expr = _addr_expr(rule[field], side, family, groups)
            if expr is None:
                # The rule does not apply to this family (e.g. an IPv4-only
                # group in the ip6 pass); skip rather than emit a broken rule.
                return None
            parts.append(expr)

    for field, side in (("src_port", "sport"), ("dst_port", "dport")):
        if rule.get(field):
            parts.append(_port_expr(rule[field], side))

    if rule.get("mac"):
        parts.append(f"ether saddr {rule['mac']}")
    if rule.get("dscp") is not None:
        parts.append(f"{family} dscp {rule['dscp']}")

    schedule = schedules.get(rule.get("schedule") or "")
    if schedule:
        expr = _schedule_expr(schedule)
        if expr:
            parts.append(expr)

    parts.append("counter")
    if rule.get("log"):
        parts.append(f'log prefix "sbegw-{rule["id"]}: " level info')
    parts.append(VERDICTS.get(rule.get("action", "drop"), "drop"))
    parts.append(f'comment "{rule["id"]}"')
    return " ".join(p for p in parts if p)


def _render_nat_table(cfg: dict[str, Any], nat: dict[str, Any],
                      wan_interfaces: dict[str, str],
                      networks: dict[str, Any]) -> list[str]:
    lines = [f"table ip {TABLE}_nat {{",
             "    chain prerouting {",
             "        type nat hook prerouting priority -100; policy accept;"]

    for fwd in nat.get("port_forwards", []):
        if not fwd.get("enabled", True):
            continue
        proto = fwd.get("protocol", "tcp")
        protos = ["tcp", "udp"] if proto == "tcp-udp" else [proto]
        wan = fwd.get("wan", "any")
        iface = wan_interfaces.get(wan) if wan != "any" else None
        target = fwd["internal_address"]
        dports = fwd["external_port"]
        to_port = fwd.get("internal_port", dports)
        for p in protos:
            match = []
            if iface:
                match.append(f"iifname \"{iface}\"")
            else:
                match.append("iifname @zone_wan_ifaces")
            match.append(f"{p} dport {dports}")
            if fwd.get("source"):
                match.append(f"ip saddr {fwd['source']}")
            lines.append("        " + " ".join(match) +
                         f" counter dnat to {target}:{to_port} "
                         f"comment \"{fwd['id']}\"")

    for entry in nat.get("one_to_one", []):
        if not entry.get("enabled", True):
            continue
        lines.append(f"        ip daddr {entry['external']} counter dnat to "
                     f"{entry['internal']} comment \"1:1 {entry.get('id', '')}\"")
    lines.append("    }")

    lines += ["    chain postrouting {",
              "        type nat hook postrouting priority 100; policy accept;"]
    if nat.get("masquerade", True):
        for wan_id, iface in sorted(wan_interfaces.items()):
            lines.append(f"        oifname \"{iface}\" counter masquerade "
                         f"comment \"masq {wan_id}\"")
    if nat.get("hairpin", True):
        # NAT reflection: a LAN client reaching its own public IP is SNAT'd to
        # the gateway so the reply comes back through the gateway.
        for nid, net in networks.items():
            subnet = net.get("subnet")
            if not subnet:
                continue
            network = subnet.rsplit("/", 1)
            lines.append(f"        ip saddr {subnet} ip daddr {subnet} "
                         f"ct status dnat counter masquerade "
                         f"comment \"hairpin {nid}\"")
    for entry in nat.get("one_to_one", []):
        if entry.get("enabled", True):
            lines.append(f"        ip saddr {entry['internal']} counter snat to "
                         f"{entry['external']}")
    lines.append("    }")

    # Interface set referenced by the DNAT rules above.
    lines.insert(1, "    set zone_wan_ifaces {")
    lines.insert(2, "        type ifname")
    if wan_interfaces:
        lines.insert(3, "        elements = " +
                     "{ " + ", ".join(f'"{i}"' for i in sorted(set(wan_interfaces.values()))) + " }")
        lines.insert(4, "    }")
    else:
        lines.insert(3, "    }")
    lines.append("}")
    return lines


def _render_mangle_table(cfg: dict[str, Any],
                         wan_interfaces: dict[str, str]) -> list[str]:
    """Policy-routing marks and DSCP handling."""
    routes = cfg.get("policy_routes", [])
    if not routes:
        return []
    lines = [f"table inet {TABLE}_mangle {{",
             "    chain prerouting {",
             "        type filter hook prerouting priority -150; policy accept;"]
    for index, route in enumerate(routes, start=1):
        if not route.get("enabled", True):
            continue
        parts = []
        if route.get("src_network_subnet"):
            parts.append(f"ip saddr {route['src_network_subnet']}")
        if route.get("src_address"):
            parts.append(f"ip saddr {route['src_address']}")
        if route.get("dst_address"):
            parts.append(f"ip daddr {route['dst_address']}")
        if route.get("protocol") and route["protocol"] != "any":
            parts.append(_proto_expr(route["protocol"]))
        if route.get("dst_port"):
            parts.append(_port_expr(route["dst_port"], "dport"))
        if route.get("mac"):
            parts.append(f"ether saddr {route['mac']}")
        mark = route.get("mark") or (0x100 + index)
        parts.append(f"counter meta mark set {hex(mark)}")
        parts.append(f'comment "pbr-{route.get("id", index)}"')
        lines.append("        " + " ".join(parts))
    lines += ["    }", "}"]
    return lines


def apply_ruleset(text: str) -> tuple[bool, str]:
    """Validate then atomically install the ruleset."""
    write_atomic(RULESET_PATH, text, mode=0o600)
    try:
        run(["nft", "-c", "-f", RULESET_PATH], timeout=30.0)
    except ToolError as exc:
        return False, f"ruleset rejected: {exc.stderr}"
    except OSError as exc:
        return False, f"nft unavailable: {exc}"
    try:
        run(["nft", "-f", RULESET_PATH], timeout=30.0)
    except ToolError as exc:
        return False, f"ruleset apply failed: {exc.stderr}"
    return True, "ruleset applied"


def counters() -> list[dict[str, Any]]:
    """Per-rule packet/byte counters with their comment, for the firewall UI."""
    data = run_json(["nft", "-j", "list", "table", "inet", TABLE], default=None)
    if not data:
        return []
    out: list[dict[str, Any]] = []
    for item in data.get("nftables", []):
        rule = item.get("rule")
        if not rule:
            continue
        counter = None
        for expr in rule.get("expr", []):
            if "counter" in expr:
                counter = expr["counter"]
        if counter is None:
            continue
        out.append({
            "chain": rule.get("chain"),
            "handle": rule.get("handle"),
            "comment": rule.get("comment"),
            "packets": counter.get("packets", 0),
            "bytes": counter.get("bytes", 0),
        })
    return out


def flush() -> bool:
    ok = True
    for table in (f"inet {TABLE}", f"ip {TABLE}_nat", f"inet {TABLE}_mangle"):
        family, name = table.split()
        run_ok(["nft", "delete", "table", family, name])
    return ok
